[Rainmeter]
Update       =1000
ContextTitle =Settings
ContextAction=[!ActivateConfig "#RootConfig#" "Settings.ini"][!Move (#CurrentConfigX#+(#S#*#SkinWidth#)+10) #CurrentConfigY# "#RootConfig#"]

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc
@Include4=#@#Players/#Plugin#.inc
SkinWidth =60
SkinHeight=60

; ----------------------------------------- Cover

[CoverDisplay]
Meter=Image
X    =(#S#*(#Border#=1 && #CoverP#=1 ? 18:10)+#ShadowR#)
Y    =(#S#*(#Border#=1 && #CoverP#=1 ? 18:10)+#ShadowR#)
W    =(#S#*(#SkinWidth# -(#Border#=1 && #CoverP#=1 ? 40:20)))
H    =(#S#*(#SkinHeight#-(#Border#=1 && #CoverP#=1 ? 40:20)))
LeftMouseUpAction  =["[OpenDirectory]"]
DynamicVariables   =1
PreserveAspectRatio=2
MeasureName        =Cover

[OpenDirectory]
Measure=String
String =[Player]
DynamicVariables=1
RegExpSubstitute=1
Substitute      ="\\[^\\]*$":""

[LocalFilesCheck]
Measure=String
String =#Plugin#
IfMatch=NowPlaying

IfMatchAction   =[!SetOption OpenDirectory "Substitute" ""\\[^\\]*$":"""]
IfNotMatchAction=[!SetOption OpenDirectory "Substitute" ""]

; ----------------------------------------- Dummy Meters

[Prev]
Meter =String
Hidden=1
[Next]
Meter =String
Hidden=1
[PlayPause]
Meter =String
Hidden=1
[TrackDisplay]
Meter =String
Hidden=1
[AlbumDisplay]
Meter =String
Hidden=1
[ArtistDisplay]
Meter =String
Hidden=1
[PositionDisplay]
Meter =String
Hidden=1