[Rainmeter]
Update       =1000
AccurateText =1
ContextTitle =Settings
ContextAction =[!ActivateConfig "#RootConfig#" "Settings.ini"][!Move (#CurrentConfigX#+(#S#*#SkinWidth#)+10) #CurrentConfigY# "#RootConfig#"]

OnRefreshAction=["#@#Focus.exe" "#PROGRAMPATH#Rainmeter.exe" "#CurrentConfig#"]

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc
@Include4=#@#Players/#Plugin#.inc
SkinWidth =(#ScreenAreaWidth#)
SkinHeight=14
Border    =0

; ----------------------------------------- Clock

[Loop]
Measure   =Loop
StartValue=0
EndValue  =1

[Time00]
Measure=Time
Format =%I:%M   -   %a, %b %d

[Time01]
Measure=Time
Format =%I:%M  %p   -   %a, %b %d

[Time10]
Measure=Time
Format =%H:%M   -   %a, %b %d

[Time11]
Measure=Time
Format =%H:%M   -   %a, %b %d

[TimeDisplay]
Meter      =String
MeterStyle =TimeDate
MeasureName=Time#24Hr##AMPM#
InlineSetting =Face | #Font#
InlineSetting2=Size | (#S#*#FontSZ#)
InlineSetting3=Color| #ColorFG#
InlineSetting4=Color| #ColorA1#
InlinePattern4=AM|PM
InlineSetting5=Color|#ColorFG#,([Loop]*255)
InlinePattern5=:
InlineSetting6=Face | Siji
InlineSetting7=Size | (#S#*9)
InlinePattern6=[\xEA5A]
InlinePattern7=[\xEA5A]
Text          =[\xEA5A] %1
StringAlign   =LeftCenter
X=(#S#*#SkinHeight#+#ShadowR#)
Y=(#S#*#SkinHeight#/2+#ShadowR#)

DynamicVariables=1

; ----------------------------------------- Music Info

[TrackDisplay]
Meter=String
MeterStyle    =TrackInfo
InlineSetting4=Face | Siji
InlineSetting5=Size | (#S#*9)
InlinePattern4=#PlayPauseC#
InlinePattern5=#PlayPauseC#
InlineSetting6=Color| #ColorA1#
InlinePattern6=#PlayPauseC#|\\\\
StringAlign   =CenterCenter
Antialias     =#AA#
UpdateDivider =1
ClipString    =0
Text=%1 \\ %2 \\ %3
X   =(#SkinWidth# /2+#ShadowR#)
Y   =(#SkinHeight#/2+#ShadowR#)
H   =(#S#*20)
W   =

LeftMouseUpAction=[!CommandMeasure Player "PlayPause"]

[Prev]
Meter=String
MeterStyle=Controls
Text =[\xEA24]
X    =([TrackDisplay:X]-40+#ShadowR#)
Y    =(#SkinHeight#/2+#ShadowR#)
W    =(#S#*20)
H    =(#S#*20)
DynamicVariables=1
UpdateDivider   =1

LeftMouseUpAction=[!CommandMeasure Player "Previous"]

[Next]
Meter=String
MeterStyle=Controls
Text =[\xE994]
X    =([TrackDisplay:X]+[TrackDisplay:W]+40+#ShadowR#)
Y    =(#SkinHeight#/2+#ShadowR#)
W    =(#S#*20)
H    =(#S#*20)
DynamicVariables=1
UpdateDivider   =1

LeftMouseUpAction=[!CommandMeasure Player "Next"]

; ----------------------------------------- Progress Bar

[ProgressDisplay]
Meter =Shape
Group =Progress
; Invisible Background
Shape =Rectangle 0,-5,300,12   | Extend Mods | FillColor 0,0,0,1
; Bar
Shape2=Rectangle 0,00,300,2    | Extend Mods | FillColor #ColorA2#,100
Shape3=Rectangle 0,00,([DragCalc]*3),2    | Extend Mods | FillColor #ColorA1#
Mods  =StrokeWidth 0 | Scale #S#,#S#,0,0
X     =(#S#*(#SkinWidth#-300-#SkinHeight#)+#ShadowR#)
Y     =(#S#*(#SkinHeight#/02)+#ShadowR#-1)

LeftMouseDownAction=[!CommandMeasure Drag "Start"]
DynamicVariables   =1

[PositionDisplay]
Meter       =String
Group       =Progress
MeasureName =Position
MeasureName2=Duration
MeterStyle  =TrackInfo
StringAlign =RightCenter
InlineSetting4=Color| #ColorA1#
InlinePattern4=\\\\
Text=%1 \\ %2
X   =(#S#*(#SkinWidth#-310-#SkinHeight#)+#ShadowR#)
Y   =(#S#*(#SkinHeight#/02)+#ShadowR#)
H   =(#S#*20)
UpdateDivider=1

[Drag]
Measure=Plugin
Plugin =Mouse
Group  =Progress
LeftMouseDragAction=[!SetOption DragCalc "Formula" "Clamp(($MouseX$-[ProgressDisplay:X])/(#S#*([ProgressDisplay:W]/100)), 0, 99.9)"][!UpdateMeasure DragCalc][!CommandMeasure Player "SetPosition [DragCalc]"][!UpdateMeterGroup Progress][!Redraw]
LeftMouseUpAction  =[!SetOption DragCalc "Formula" "Progress"][!CommandMeasure Drag "Stop"]
RelativeToSkin     =1
RequireDragging    =1

[DragCalc]
Measure=Calc
Group  =Progress
Formula=Progress
