[Rainmeter]
Update        =1000
AccurateText  =1
ContextTitle  =Settings
ContextAction =[!ActivateConfig "#RootConfig#" "Settings.ini"][!Move (#CurrentConfigX#+(#S#*#SkinWidth#)+10) #CurrentConfigY# "#RootConfig#"]

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc
SkinWidth =110
SkinHeight=60

; ----------------------------------------- Measures

[BinNum]
Measure=Plugin
Plugin =RecycleManager
RecycleType=Count

IfCondition   =(#CurrentSection# <> 1)
IfTrueAction  =[!SetOption BinString "Text" "[BinNum] Items#CRLF#%1"]

[BinSize]
Measure=Plugin
Plugin =RecycleManager
RecycleType   =Size
OnChangeAction=[!Refresh]

; ----------------------------------------- Recycle Icon

[Icon]
Meter=String
Text =[\xE86F]
InlineSetting =Face | Siji
InlineSetting2=Size | (#S#*9)
InlineSetting3=Color| #ColorFG#
StringAlign=CenterCenter
SolidColor =#ColorFG#,40
Antialias  =#AA#
X=(#S#*(#SkinHeight#/02)+#ShadowR#)
Y=(#S#*(#SkinHeight#/02)+#ShadowR#)
W=(#S#*(#SkinHeight#-20))
H=(#S#*(#SkinHeight#-20))

MouseOverAction    =[!SetOption #CurrentSection# "InlineSetting3" "Color|#ColorA1#"][!SetOption #CurrentSection# "SolidColor" "#ColorA2#,40"][!UpdateMeter #CurrentSection#][!Redraw]
MouseLeaveAction   =[!SetOption #CurrentSection# "InlineSetting3" "Color|#ColorFG#"][!SetOption #CurrentSection# "SolidColor" "#ColorFG#,40"][!UpdateMeter #CurrentSection#][!Redraw]
LeftMouseDownAction=[!SetOption #CurrentSection# "InlineSetting3" "Color|#ColorA2#"][!SetOption #CurrentSection# "SolidColor" "#ColorA2#,20"][!UpdateMeter #CurrentSection#][!Redraw]
LeftMouseUpAction  =[!SetOption #CurrentSection# "InlineSetting3" "Color|#ColorFG#"][!SetOption #CurrentSection# "SolidColor" "0,0,0,1     "][!UpdateMeter #CurrentSection#][!Redraw][!ShowMeterGroup BinPrompt][!HideMeter Icon][!Update]

; ----------------------------------------- Recycle String

[BinString]
Meter=String
Text =[BinNum] Item#CRLF#%1
MeasureName   =BinSize
InlineSetting =Face | #Font#
InlineSetting2=Size | (#S#*#FontSZ#)
InlineSetting3=Color| #ColorFG#
InlineSetting4=Color| #ColorA2#
InlinePattern4=#CRLF#(.*)
StringAlign=LeftCenter
ClipString =1
AutoScale  =1
Antialias  =#AA#
X=(#S#*#SkinHeight#+#ShadowR#)
Y=(#S#*(#SkinHeight#/02)+#ShadowR#)
W=(#S#*(#SkinWidth#-#SkinHeight#-10))
H=(#S#*(#SkinHeight#-20))

DynamicVariables=1

; ----------------------------------------- Recycle Bin Prompt

[PromptBG]
Meter=Shape
Group=BinPrompt
Shape=Rectangle (#S#*#ShadowR#),(#S#*#ShadowR#),#SkinWidth#,#SkinHeight# | StrokeWidth 0 | FillColor #ColorBG# | Scale #S#,#S#,0,0
UpdateDivider=-1
Hidden       =1

[Prompt]
Meter=String
MeterStyle =BinPrompt
Text =Empty Recycle Bin?
X    =(#S#*(#SkinWidth#/2)+#ShadowR#)
Y    =(#S#*15+#ShadowR#)

MouseOverAction =
MouseLeaveAction=

[Yes]
Meter=String
MeterStyle=BinPrompt
X    =(#S#*25+#ShadowR#)
Y    =(#S#*(#SkinHeight#/2)+#ShadowR#)

LeftMouseUpAction=[!CommandMeasure BinNum "EmptyBinSilent"][!HideMeterGroup BinPrompt][!ShowMeter Icon][!Update]

[No]
Meter=String
MeterStyle=BinPrompt
X    =(#S#*(#SkinWidth#-25)+#ShadowR#)
Y    =(#S#*(#SkinHeight#/2)+#ShadowR#)

LeftMouseUpAction=[!HideMeterGroup BinPrompt][!ShowMeter Icon][!Update]

[Open]
Meter=String
MeterStyle=BinPrompt
X    =(#S#*(#SkinWidth#/2)+#ShadowR#)
Y    =(#S#*(#SkinHeight#-15)+#ShadowR#)

LeftMouseUpAction=[shell:RecycleBinFolder][!HideMeterGroup BinPrompt][!ShowMeter Icon][!Update]

; ----------------------------------------- Drag and Drop

[DragNDrop]
Measure=Plugin
Plugin =Drag&Drop
Action =Delete
Bounds =0,0,100,100
