[Rainmeter]
Update        =(#Vis#=1 ? (#Smooth#=1 ? 20:40):1000)
AccurateText  =1
ContextTitle  =Settings
ContextAction =[!ActivateConfig "#RootConfig#" "Settings.ini"][!Move (#CurrentConfigX#+(#S#*#SkinWidth#)+10) #CurrentConfigY# "#RootConfig#"]

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc
@Include4=#@#Players/#Plugin#.inc
SkinWidth =300
SkinHeight=60

BarH=(#SkinHeight#/2)
BarN=(28/#BarW#)
;Visualizer Vars

; ----------------------------------------- Track Info

[TrackDisplay]
Meter         =String
MeterStyle    =TrackInfo
InlineSetting3=Color|#ColorA1#
Text =%1
Y    =(#S#*(#Album#=1 ? 15:20)+#ShadowR#)

[ArtistDisplay]
Meter=String
MeterStyle=TrackInfo
Text =%2
Y    =(#S#*(#Album#=1 ? (#SkinHeight#/2):(#SkinHeight#-20))+#ShadowR#)

[AlbumDisplay]
Meter=String
MeterStyle=TrackInfo
Hidden    =(#Album#=1 ? 0:1)
Text =%3
Y    =(#S#*(#SkinHeight#-15)+#ShadowR#)

; ----------------------------------------- Controls

[Prev]
Meter     =String
MeterStyle=Controls
Text      =[\xE9F9]
X         =(#S#*(#SkinWidth#/2)-18+#ShadowR#)

LeftMouseUpAction=[!CommandMeasure Player "Previous"]

[PlayPause]
Meter     =String
MeterStyle=Controls

LeftMouseUpAction=[!CommandMeasure Player "PlayPause"]

[Next]
Meter     =String
MeterStyle=Controls
Text      =[\xE975]

LeftMouseUpAction=[!CommandMeasure Player "Next"]

; ----------------------------------------- Visualizer

[VisInclusions]
@Include1=#@#VisMeasures/VisMeasures#Smooth#.inc
@Include2=#@#Modules/Visualizer.inc

; ----------------------------------------- Song Position

[PositionDisplay]
Meter=String
MeterStyle=PosDur
Text =%1 %2

; ----------------------------------------- Progress Bar

[ProgressDisplay]
Meter =Shape
Group =Progress
; Invisible Background
Shape =Rectangle 0,-5,#SkinWidth#,12   | Extend Mods | FillColor 0,0,0,1
; Bar
Shape2=Rectangle 0,00,#SkinWidth#,0    | Extend Mods | FillColor #ColorBG#,100
Shape3=Rectangle 0,00,([DragCalc]*((#SkinWidth#-(#S#*(#ProgType#=1 ? 0:2)))/100)),2    | Extend Mods | Extend BarCLR
; Marker
Shape4=Rectangle (#S#*[DragCalc]*((#SkinWidth#-(#S#*2))/100)),0,2,2 | Extend Mods | FillColor #ColorA1#,(#ProgType#=1 ? 0:255)
BarCLR=FillColor #ColorBG#
Mods  =StrokeWidth 0 | Scale #S#,#S#,0,0
X     =(#S#*#ShadowR#)
Y     =(#S#*(#SkinHeight#+2)+#ShadowR#)

LeftMouseDownAction=[!CommandMeasure Drag "Start"]
DynamicVariables   =1

; ----------------------------------------- Align Calc

[AlignCalc]
Measure =String
String  =#Align#
IfMatch =Left
IfMatch2=Center
IfMatch3=Right

IfMatchAction =[!SetOptionGroup TrackInfo "X" "(#S#*(#Album#=1 ? 10:15)+#ShadowR#)"][!SetOption Prev "X" "(#S#*(#SkinWidth#-(#Album#=1 ? 57:62))+#ShadowR#)"][!SetOption 0 "X" "(#S#*(#SkinWidth#-(#Album#=1 ? 72:64))+#ShadowR#)"]
IfMatchAction2=[!SetOptionGroup TrackInfo "X" "(#S#*(#SkinWidth#/02)+#ShadowR#)"][!SetOptionGroup TrackInfo "W" "(#S#*(#SkinWidth#-20)+(#Shadow#=1 ? 5:0))"][!HideMeterGroup Controls][!HideMeterGroup Bars][!HideMeter 0]
IfMatchAction3=[!SetOptionGroup TrackInfo "X" "(#S#*(#SkinWidth#-(#Album#=1 ? 10:15))+#ShadowR#)"][!SetOption Prev "X" "(#S#*(#Album#=1 ? 15:20)+#ShadowR#)"][!SetOption 0 "X" "(#S#*(#Album#=1 ? 8:16)+#ShadowR#)"]

; ----------------------------------------- Vis Calc

[VisCalc]
Measure=Calc
IfCondition =(#Vis#=0)
IfTrueAction=[!DisableMeasureGroup "Bands"]

; ----------------------------------------- Progress Type Calc

[ProgressBarCalc]
Measure=Calc
IfCondition =(#ProgType#=1)
IfTrueAction=[!SetOption ProgressDisplay "BarCLR" "FillColor #ColorA1#"]

; ----------------------------------------- Drag Calc

[Drag]
Measure=Plugin
Plugin =Mouse
Group  =Progress
LeftMouseDragAction=[!SetOption DragCalc "Formula" "Clamp(($MouseX$-[ProgressDisplay:X])/(#S#*([ProgressDisplay:W]/100)), 0, 99.9)"][!UpdateMeasure DragCalc][!CommandMeasure Player "SetPosition [DragCalc]"][!UpdateMeterGroup Progress][!Redraw]
LeftMouseUpAction  =[!SetOption DragCalc "Formula" "Progress"][!CommandMeasure Drag "Stop"]
RelativeToSkin     =1
RequireDragging    =1

[DragCalc]
Measure=Calc
Group  =Progress
Formula=Progress
