[Rainmeter]
Update       =1000
AccurateText =1
ContextTitle  =Settings
ContextAction =[!ActivateConfig "#RootConfig#" "Settings.ini"][!Move (#CurrentConfigX#+(#S#*#SkinWidth#)+10) #CurrentConfigY# "#RootConfig#"]

OnRefreshAction=[!Update][!Redraw]

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc
SkinWidth =60
SkinHeight=120
Update=[!UpdateMeasureGroup ColorSliders][!UpdateMeterGroup ColorSliders][!Redraw]
S=#Scale#

; ----------------------------------------- Loop

[Loop]
Measure   =Loop
StartValue=0
EndValue  =1
LoopCount =1

IfCondition  =(Loop=0)
IfTrueAction =[!ShowMeter ColorText][!Redraw]
IfFalseAction=[!HideMeter ColorText][!Redraw]

; ----------------------------------------- Color Swatch

[ColorString]
Measure=String
Group  =ColorSliders
String =[RSCalc],[GSCalc],[BSCalc]

OnChangeAction  =[!CommandMeasure Loop "Reset"]
DynamicVariables=1

[ColorSwatch]
Meter=Shape
Group=ColorSliders
Shape=Rectangle (#S#*10+#ShadowR#),(#S#*10+#ShadowR#),(#SkinWidth#-20),(#SkinHeight#/3) | Scale #S#,#S#,0,0 | StrokeWidth 0 | FillColor [ColorString]

DynamicVariables   =1
MouseOverAction    =[!ShowMeterGroup SetColorVars][!UpdateMeterGroup SetColorVars][!Redraw]
MouseLeaveAction   =[!HideMeterGroup SetColorVars][!UpdateMeterGroup SetColorVars][!Redraw]
LeftMouseDownAction=[!ShowMeter ColorText][!Redraw]
LeftMouseUpAction  =[!HideMeter ColorText][!Redraw]

[SetColorA1]
Meter     =String
Text      =Set A1
MeterStyle=SetColor
Y         =(#S#*10+#ShadowR#)

LeftMouseUpAction=[!WriteKeyValue Variables "ColorA1" "[ColorString]" "#@#Variables.inc"][!Refresh *]

[SetColorA2]
Meter      =String
Text       =Set A2
MeterStyle =SetColor

LeftMouseUpAction=[!WriteKeyValue Variables "ColorA2" "[ColorString]" "#@#Variables.inc"][!Refresh *]

; ----------------------------------------- Color Input

[ColorText]
Meter      =String
Group      =ColorSliders
MeterStyle =ColorLabel
MeasureName=ColorString
SolidColor =0,0,0,#Alpha#
X=(#S#*(#SkinWidth#/2)+#ShadowR#)
Y=(#S#*(#SkinWidth#/2)-(#FontSZ#/2)+#ShadowR#)
W=(#S#*(#SkinWidth#))
DynamicVariables=1

; ----------------------------------------- Color Sliders

; ----------------------------------------- Red

[RText]
Meter=String
MeterStyle=ColorLabel
Text =Red
Y    =(#S#*((#SkinHeight#/3)+#FontSZ#+2)+#ShadowR#)

[RSlider]
Meter =Shape
Group =ColorSliders
Shape =Rectangle 0                                    ,0,(#SkinWidth#-20),10 | Extend Mods | FillColor 0,0,0,(#Alpha#/2)
Shape2=Rectangle (#S#*([RSCalc]/255)*(#SkinWidth#-22)),0,2,10  | Extend Mods | FillColor 255,255,255

MeterStyle           =ColorSlider
LeftMouseDownAction  =[!CommandMeasure RSMouse "Start"]
MouseScrollDownAction=[!SetOption RSCalc "Formula" "Clamp(([RSCalc]-1), 0, 255)"][!WriteKeyValue RSCalc "Formula" "Clamp(([RSCalc]-1), 0, 255)"][!Update]#Update#
MouseScrollUpAction  =[!SetOption RSCalc "Formula" "Clamp(([RSCalc]+1), 0, 255)"][!WriteKeyValue RSCalc "Formula" "Clamp(([RSCalc]+1), 0, 255)"][!Update]#Update#

[RSMouse]
Measure=Plugin
Plugin =Mouse
Group  =ColorSliders
LeftMouseDragAction=[!SetOption RSCalc "Formula" "Round(Clamp(((($MouseX$-[RSlider:X])/[RSlider:W])*255), 0, 255))"]#Update#
LeftMouseUpAction  =[!CommandMeasure #CurrentSection# "Stop"][!WriteKeyValue RSCalc "Formula" [RSCalc]]
RelativeToSkin     =1
RequireDragging    =1

[RSCalc]
Measure=Calc
Group  =ColorSliders
Formula=45

; ----------------------------------------- Green

[GText]
Meter=String
MeterStyle=ColorLabel
Text =Green

[GSlider]
Meter =Shape
Group =ColorSliders
Shape =Rectangle 0                                    ,0,(#SkinWidth#-20),10 | Extend Mods | FillColor 0,0,0,(#Alpha#/2)
Shape2=Rectangle (#S#*([GSCalc]/255)*(#SkinWidth#-22)),0,2,10  | Extend Mods | FillColor 255,255,255

MeterStyle           =ColorSlider
LeftMouseDownAction  =[!CommandMeasure GSMouse "Start"][!SetOption ColorText "MeasureName" "ColorString"][!SetOption ColorText "Text" ""]
MouseScrollDownAction=[!SetOption GSCalc "Formula" "Clamp(([GSCalc]-1), 0, 255)"][!WriteKeyValue GSCalc "Formula" "Clamp(([GSCalc]-1), 0, 255)"][!Update]#Update#
MouseScrollUpAction  =[!SetOption GSCalc "Formula" "Clamp(([GSCalc]+1), 0, 255)"][!WriteKeyValue GSCalc "Formula" "Clamp(([GSCalc]+1), 0, 255)"][!Update]#Update#

[GSMouse]
Measure=Plugin
Plugin =Mouse
Group  =ColorSliders
LeftMouseDragAction=[!SetOption GSCalc "Formula" "Round(Clamp(((($MouseX$-[GSlider:X])/[GSlider:W])*255), 0, 255))"]#Update#
LeftMouseUpAction  =[!CommandMeasure #CurrentSection# "Stop"][!WriteKeyValue GSCalc "Formula" [GSCalc]]
RelativeToSkin     =1
RequireDragging    =1

[GSCalc]
Measure=Calc
Group  =ColorSliders
Formula=Clamp((111-1), 0, 255)

; ----------------------------------------- Blue

[BText]
Meter=String
MeterStyle=ColorLabel
Text =Blue

[BSlider]
Meter =Shape
Group =ColorSliders
Shape =Rectangle 0                                    ,0,(#SkinWidth#-20),10 | Extend Mods | FillColor 0,0,0,(#Alpha#/2)
Shape2=Rectangle (#S#*([BSCalc]/255)*(#SkinWidth#-22)),0,2,10  | Extend Mods | FillColor 255,255,255

MeterStyle           =ColorSlider
LeftMouseDownAction  =[!CommandMeasure BSMouse "Start"][!SetOption ColorText "MeasureName" "ColorString"][!SetOption ColorText "Text" ""]
MouseScrollDownAction=[!SetOption BSCalc "Formula" "Clamp(([BSCalc]-1), 0, 255)"][!WriteKeyValue BSCalc "Formula" "Clamp(([BSCalc]-1), 0, 255)"][!Update]#Update#
MouseScrollUpAction  =[!SetOption BSCalc "Formula" "Clamp(([BSCalc]+1), 0, 255)"][!WriteKeyValue BSCalc "Formula" "Clamp(([BSCalc]+1), 0, 255)"][!Update]#Update#

[BSMouse]
Measure=Plugin
Plugin =Mouse
Group  =ColorSliders
LeftMouseDragAction=[!SetOption BSCalc "Formula" "Round(Clamp(((($MouseX$-[BSlider:X])/[BSlider:W])*255), 0, 255))"]#Update#
LeftMouseUpAction  =[!CommandMeasure #CurrentSection# "Stop"][!WriteKeyValue BSCalc "Formula" [BSCalc]]
RelativeToSkin     =1
RequireDragging    =1

[BSCalc]
Measure=Calc
Group  =ColorSliders
Formula=Clamp((139+1), 0, 255)
