[Rainmeter]
Update        =1000
AccurateText  =1
ContextTitle  =Settings
ContextAction =[!ActivateConfig "#RootConfig#" "Settings.ini"][!Move (#CurrentConfigX#+(#S#*#SkinWidth#)+10) #CurrentConfigY# "#RootConfig#"]

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc
SkinWidth =180
SkinHeight=60

; ----------------------------------------- Calcs

[ModeCalc]
Measure      =Calc
IfCondition  =((#SkinWidth#-20) < #SkinHeight#)
IfTrueAction =[!HideMeter Slider][!HideMeter AudioDisplay]

[IconCalc]
Measure =String
String  =[Audio]
IfMatch =Headset

IfMatchAction   =[!SetOption Icon "Text" "[\xE971]"]
IfNotMatchAction=[!SetOption Icon "Text" "[\xE978]"]
DynamicVariables=1

[Audio]
Measure=Plugin
Plugin =Win7AudioPlugin

OnChangeAction=[!UpdateMeter AudioDisplay][!Update][!Redraw]

; ----------------------------------------- Icon

[Icon]
Meter=String
Text =[\xE971]
InlineSetting =Face | Siji
InlineSetting2=Size | (#S#*9)
InlineSetting3=Color| #ColorFG#
StringAlign=CenterCenter
SolidColor =#ColorFG#,40
Antialias  =#AA#
X=(#S#*(#SkinHeight#/02)+#ShadowR#)
Y=(#S#*(#SkinHeight#/02)+#ShadowR#)
W=(#S#*(#SkinHeight#-20))
H=(#S#*(#SkinHeight#-20))

MouseOverAction    =[!SetOption #CurrentSection# "InlineSetting3" "Color|#ColorA1#"][!SetOption #CurrentSection# "SolidColor" "#ColorA2#,40"][!UpdateMeter #CurrentSection#][!Redraw]
MouseLeaveAction   =[!SetOption #CurrentSection# "InlineSetting3" "Color|#ColorFG#"][!SetOption #CurrentSection# "SolidColor" "#ColorFG#,40"][!UpdateMeter #CurrentSection#][!Redraw]
LeftMouseDownAction=[!SetOption #CurrentSection# "InlineSetting3" "Color|#ColorA2#"][!SetOption #CurrentSection# "SolidColor" "#ColorA2#,20"][!UpdateMeter #CurrentSection#][!Redraw]
LeftMouseUpAction  =[!SetOption #CurrentSection# "InlineSetting3" "Color|#ColorFG#"][!SetOption #CurrentSection# "SolidColor" "#ColorFG#,40"][!UpdateMeter #CurrentSection#][!Redraw][!CommandMeasure "Audio" "ToggleNext"][!Refresh "#RootConfig#\Media"][!Update][!Redraw]

; ----------------------------------------- String

[AudioDisplay]
Meter=String
Text =%1 - [Audio:]%
MeasureName   =Audio
InlineSetting =Face | #Font#
InlineSetting2=Size | (#S#*#FontSZ#)
InlineSetting3=Color| #ColorFG#
StringAlign=LeftCenter
ClipString =1
Antialias  =#AA#
X=(#S#*#SkinHeight#+#ShadowR#)
Y=(#S#*(#SkinHeight#/02)+#ShadowR#)
W=(#S#*(#SkinWidth#-#SkinHeight#-30))
H=(#S#*(#SkinHeight#-20))

UpdateDivider        =-1
DynamicVariables     =1
MouseScrollUpAction  =[!CommandMeasure "Audio" "ChangeVolume +1"][!UpdateMeter AudioDisplay][!Update][!Redraw]
MouseScrollDownAction=[!CommandMeasure "Audio" "ChangeVolume -1"][!UpdateMeter AudioDisplay][!Update][!Redraw]

; ----------------------------------------- Volume Slider

[Slider]
Meter =Shape
; Bar
Shape =Rectangle 0,0,10,(#SkinHeight#-20) | Extend Mods | FillColor #ColorFG#,40
; Marker
Shape2=Rectangle 0,((#SkinHeight#-23)-([DragCalc]/100)*(#SkinHeight#-23)),10,3 | Extend Mods | FillColor #ColorA1#
Mods  =StrokeWidth 0 | Scale #S#,#S#,0,0
X     =(#S#*(#SkinWidth#-20)+#ShadowR#)
Y     =(#S#*10+#ShadowR#)

MouseScrollUpAction  =[!CommandMeasure "Audio" "ChangeVolume +1"][!UpdateMeter AudioDisplay][!Update][!Redraw]
MouseScrollDownAction=[!CommandMeasure "Audio" "ChangeVolume -1"][!UpdateMeter AudioDisplay][!Update][!Redraw]
LeftMouseDownAction  =[!CommandMeasure Drag "Start"]
DynamicVariables     =1

[Drag]
Measure=Plugin
Plugin =Mouse
LeftMouseDragAction=[!SetOption DragCalc "Formula" "Clamp((100-((($MouseY$-10)/(#SkinHeight#-20))*100)),0,100)"][!UpdateMeasure #CurrentSection#][!UpdateMeasure DragCalc][!CommandMeasure "Audio" "SetVolume [DragCalc]"][!Update][!Redraw]
LeftMouseUpAction  =[!SetOption DragCalc "Formula" "Audio"][!CommandMeasure Drag "Stop"]
RelativeToSkin     =1
RequireDragging    =1

[DragCalc]
Measure=Calc
Formula=Audio