[Rainmeter]
Update        =5000
AccurateText  =1
ContextTitle  =Settings
ContextAction =[!ActivateConfig "#RootConfig#" "Settings.ini"][!Move (#CurrentConfigX#+(#S#*#SkinWidth#)+10) #CurrentConfigY# "#RootConfig#"]

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc
SkinWidth =160
SkinHeight=180

; ----------------------------------------- Top Processes

[Process1]
Measure=Plugin
Plugin =UsageMonitor
Percent=1
Alias=GPU
Index=1

[Process1Calc]
Measure=Calc
Formula=Process1
OnChangeAction=[!UpdateMeter Process1Display]
IfCondition   =(#CurrentSection#<1)
IfTrueAction  =[!HideMeter Process1Display]
IfFalseAction =[!ShowMeter Process1Display]

[Process2]
Measure=Plugin
Plugin =UsageMonitor
Percent=1
Alias=GPU
Index=2

[Process2Calc]
Measure=Calc
Formula=Process2
OnChangeAction=[!UpdateMeter Process2Display]
IfCondition   =(#CurrentSection#<1)
IfTrueAction  =[!HideMeter Process2Display]
IfFalseAction =[!ShowMeter Process2Display]

[Process3]
Measure=Plugin
Plugin =UsageMonitor
Percent=1
Alias=GPU
Index=3

[Process3Calc]
Measure=Calc
Formula=Process3
OnChangeAction=[!UpdateMeter Process3Display]
IfCondition   =(#CurrentSection#<1)
IfTrueAction  =[!HideMeter Process3Display]
IfFalseAction =[!ShowMeter Process3Display]

[Process4]
Measure=Plugin
Plugin =UsageMonitor
Percent=1
Alias=GPU
Index=4

[Process4Calc]
Measure=Calc
Formula=Process4
OnChangeAction=[!UpdateMeter Process4Display]
IfCondition   =(#CurrentSection#<1)
IfTrueAction  =[!HideMeter Process4Display]
IfFalseAction =[!ShowMeter Process4Display]

[Process5]
Measure=Plugin
Plugin =UsageMonitor
Percent=1
Alias=GPU
Index=5

[Proces5Calc]
Measure=Calc
Formula=Process5
OnChangeAction=[!UpdateMeter Process5Display]
IfCondition   =(#CurrentSection#<1)
IfTrueAction  =[!HideMeter Process5Display]
IfFalseAction =[!ShowMeter Process5Display]

[Process6]
Measure=Plugin
Plugin =UsageMonitor
Percent=1
Alias=GPU
Index=6

[Proces6Calc]
Measure=Calc
Formula=Process6
OnChangeAction=[!UpdateMeter Process6Display]
IfCondition   =(#CurrentSection#<1)
IfTrueAction  =[!HideMeter Process6Display]
IfFalseAction =[!ShowMeter Process6Display]

[Process7]
Measure=Plugin
Plugin =UsageMonitor
Percent=1
Alias=GPU
Index=7

[Proces7Calc]
Measure=Calc
Formula=Process7
OnChangeAction=[!UpdateMeter Process7Display]
IfCondition   =(#CurrentSection#<1)
IfTrueAction  =[!HideMeter Process7Display]
IfFalseAction =[!ShowMeter Process7Display]


; ----------------------------------------- Display

[Title]
Meter=String
MeterStyle    =Process
InlineSetting5=Underline
Text =Top GPU Processes:
Y    =(#S#*12+#ShadowR#)

MouseOverAction  =[!SetOption #CurrentSection# "SolidColor" "#ColorFG#,100"][!Update]
MouseLeaveAction =[!SetOption #CurrentSection# "SolidColor" "#ColorFG#,000"][!Update]
LeftMouseUpAction=["Taskmgr.exe"]

[Process1Display]
Meter=String
MeterStyle  =Process
MeasureName =Process1
MeasureName2=Process1Calc

[Process2Display]
Meter=String
MeterStyle  =Process
MeasureName =Process2
MeasureName2=Process2Calc

[Process3Display]
Meter=String
MeterStyle  =Process
MeasureName =Process3
MeasureName2=Process3Calc

[Process4Display]
Meter=String
MeterStyle  =Process
MeasureName =Process4
MeasureName2=Process4Calc

[Process5Display]
Meter=String
MeterStyle  =Process
MeasureName =Process5
MeasureName2=Process5Calc

[Process6Display]
Meter=String
MeterStyle  =Process
MeasureName =Process6
MeasureName2=Process6Calc

[Process7Display]
Meter=String
MeterStyle  =Process
MeasureName =Process7
MeasureName2=Process7Calc