[Rainmeter]
Update        =-1
AccurateText  =1
ContextTitle  =Variables
ContextAction =["#@#Variables.inc"]
ContextTitle2 =Styles
ContextAction2=["#@#Styles.inc"]
ContextTitle3 =Resources Folder
ContextAction3=["#@#"]
SkinHeight    =(#S#*#SkinHeight#+(#ShadowR#*2))

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules\Background.inc
SkinWidth =300
SkinHeight=260
MedPlayer =Web

ScrollPrcnt=10
; Percentage of height to scroll
ScrollH    =400
;Total Height to scroll

Accent1=120,220,140
Accent2=240,240,160
Accent3=140,140,220

YColor =080,200,080
NColor =100,100,200

; ----------------------------------------- Background

[Background]
Meter =Shape
Shape =Rectangle 0,0,(#SkinWidth#-00),(#SkinHeight#-00) | Extend Mods | StrokeWidth 0 | FillColor #ColorBG#,#Alpha#
Shape2=Rectangle 5,5,(#SkinWidth#-10),(#SkinHeight#-10) | Extend Mods | StrokeWidth 2 | FillColor #ColorBG#,0000000 | StrokeColor #ColorA2#,(#Alpha#/4*#Border#)
Mods  =Scale #S#,#S#,0,0

MouseScrollDownAction=[!SetOption Scroll "Formula" "(Clamp((#S#*([Scroll]+#ScrollPrcnt#)), 0, 100))"][!WriteKeyValue Scroll "Formula" "([Scroll]+([Scroll]=100 ? 0:#ScrollPrcnt#))"][!Update][!Redraw]
MouseScrollUpAction  =[!SetOption Scroll "Formula" "(Clamp((#S#*([Scroll]-#ScrollPrcnt#)), 0, 100))"][!WriteKeyValue Scroll "Formula" "([Scroll]-([Scroll]=000 ? 0:#ScrollPrcnt#))"][!Update][!Redraw]
MouseActionCursor=0
DynamicVariables =1
UpdateDivider    =-1

[ScrollBar]
Meter =Shape
Shape =Rectangle 00,0,11,100 | Extend Mods | FillColor 0,0,0,1
Shape2=Rectangle 04,0,02,100 | Extend Mods | FillColor #ColorFG#,#Alpha#
Mods  =StrokeWidth 0 | Scale #S#,#S#,0,0
X     =(#S#*(#SkinWidth#-10)+#ShadowR#)
Y     =(#S#*([Scroll]*((#SkinHeight#-112)/100))+6+#ShadowR#)

LeftMouseDownAction=[!CommandMeasure Drag "Start"]
DynamicVariables   =1

; ----------------------------------------- Close

[CloseShape]
Meter =Shape
Group =Close
Shape =Rectangle (#S#*2),(#S#*2),14,14 | Scale #S#,#S#,0,0 | StrokeWidth 0 | FillColor 240,100,110
Shape2=Rectangle (#S#*0),(#S#*0),18,18 | Scale #S#,#S#,0,0 | StrokeWidth 0 | FillColor 240,100,110
Shape3=Rectangle (#S#*1),(#S#*1),16,16 | Scale #S#,#S#,0,0 | StrokeWidth 0 | FillColor #ColorBG#
Shape4=Combine Shape3 | XOR Shape
Hidden=1
X     =(#S#*(#SkinWidth#-37)+#ShadowR#)
Y     =(#S#*17+#ShadowR#)
DynamicVariables=1

[CloseText]
Meter         =String
Group         =Close
Text          =X
InlineSetting =Face  | Siji
InlineSetting2=Color | #ColorFG#
InlineSetting3=Size  | (#S#*8)
StringAlign   =CenterCenter
SolidColor    =0,0,0,1
Antialias     =#AA#
X    =(#S#*09)r
Y    =(#S#*10)r
W    =(#S#*18)
H    =(#S#*18)

MouseOverAction  =[!ShowMeter CloseShape][!SetOption #CurrentSection# "InlineSetting2" "Color|255,255,255"][!UpdateMeterGroup Close][!Redraw]
MouseLeaveAction =[!HideMeter CloseShape][!SetOption #CurrentSection# "InlineSetting2" "Color|#ColorFG#  "][!UpdateMeterGroup Close][!Redraw]
LeftMouseUpAction=[!WriteKeyValue Scroll "Formula" "0"][!DeactivateConfig]

; ----------------------------------------- Media Players

[Section1]
Meter=String
MeterStyle=Section
FontColor =#Accent1#
Text =< Media Players -- > 
Y    =(#S#*20-(([Scroll]/100)*#ScrollH#)+#ShadowR#)
DynamicVariables=1

[AIMP]
Meter=String
MeterStyle=OptionP
X    =(#S#*35)
Y    =(#S#*30)r

LeftMouseUpAction=[!WriteKeyValue Variables "Plugin" "NowPlaying" "#@#Variables.inc"][!WriteKeyValue Variables "Player" "AIMP" "#@#Variables.inc"][!WriteKeyValue Variables "MedPlayer" "#CurrentSection#"][!Refresh "#RootConfig#\Media"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

[Foobar2K]
Meter=String
MeterStyle=OptionP

LeftMouseUpAction=[!WriteKeyValue Variables "Plugin" "NowPlaying" "#@#Variables.inc"][!WriteKeyValue Variables "Player" "CAD" "#@#Variables.inc"][!WriteKeyValue Variables "MedPlayer" "#CurrentSection#"][!Refresh "#RootConfig#\Media"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

[Winamp]
Meter=String
MeterStyle=OptionP

LeftMouseUpAction=[!WriteKeyValue Variables "Plugin" "NowPlaying" "#@#Variables.inc"][!WriteKeyValue Variables "Player" "Winamp" "#@#Variables.inc"][!WriteKeyValue Variables "MedPlayer" "#CurrentSection#"][!Refresh "#RootConfig#\Media"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

[MediaMonkey]
Meter=String
MeterStyle=OptionP
X   =(#S#*57)r
W   =(#S#*60)

LeftMouseUpAction=[!WriteKeyValue Variables "Plugin" "NowPlaying" "#@#Variables.inc"][!WriteKeyValue Variables "Player" "CAD" "#@#Variables.inc"][!WriteKeyValue Variables "MedPlayer" "#CurrentSection#"][!Refresh "#RootConfig#\Media"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

[iTunes]
Meter=String
MeterStyle=OptionP
X    =(#S#*35)
Y    =(#S#*20)r

LeftMouseUpAction=[!WriteKeyValue Variables "Plugin" "NowPlaying" "#@#Variables.inc"][!WriteKeyValue Variables "Player" "iTunes" "#@#Variables.inc"][!WriteKeyValue Variables "MedPlayer" "#CurrentSection#"][!Refresh "#RootConfig#\Media"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

[Spotify]
Meter=String
MeterStyle=OptionP

LeftMouseUpAction=[!WriteKeyValue Variables "Plugin" "Spotify" "#@#Variables.inc"][!WriteKeyValue Variables "Player" "Spotify" "#@#Variables.inc"][!WriteKeyValue Variables "MedPlayer" "#CurrentSection#"][!Refresh "#RootConfig#\Media"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

[Web]
Meter=String
MeterStyle=OptionP

LeftMouseUpAction=[!WriteKeyValue Variables "Plugin" "Web" "#@#Variables.inc"][!WriteKeyValue Variables "Player" "Web" "#@#Variables.inc"][!WriteKeyValue Variables "MedPlayer" "#CurrentSection#"][!Refresh "#RootConfig#\Media"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

[MusicBee]
Meter=String
MeterStyle=OptionP
X   =(#S#*57)r
W   =(#S#*60)

LeftMouseUpAction=[!WriteKeyValue Variables "Plugin" "NowPlaying" "#@#Variables.inc"][!WriteKeyValue Variables "Player" "MusicBee" "#@#Variables.inc"][!WriteKeyValue Variables "MedPlayer" "#CurrentSection#"][!Refresh "#RootConfig#\Media"][!Refresh "#RootConfig#\Media\Cover"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

[GPMDP]
Meter=String
MeterStyle=OptionP
X    =(#S#*35)
Y    =(#S#*20)r

LeftMouseUpAction=[!WriteKeyValue Variables "Plugin" "GPMDP" "#@#Variables.inc"][!WriteKeyValue Variables "Player" "GPMDP" "#@#Variables.inc"][!WriteKeyValue Variables "MedPlayer" "#CurrentSection#"][!Refresh "#RootConfig#\Media"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

[WMP]
Meter=String
MeterStyle=OptionP

LeftMouseUpAction=[!WriteKeyValue Variables "Plugin" "NowPlaying" "#@#Variables.inc"][!WriteKeyValue Variables "Player" "WMP" "#@#Variables.inc"][!WriteKeyValue Variables "MedPlayer" "#CurrentSection#"][!Refresh "#RootConfig#\Media"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

; ----------------------------------------- Colors

[Section2]
Meter=String
MeterStyle=Section
FontColor =#Accent2#
Text =< Colors ------- >
Y    =(#S#*20)r

[ColorFGSquare]
Meter=Shape
MeterStyle=Swatch
Shape=Rectangle 0,0,(#FontSZ#+2),(#FontSZ#+2) | Extend Mods | FillColor #ColorFG#
Y    =(#S#*25)r

[ColorFG]
Meter=String
MeterStyle    =OptionIT
Text =Foreground Color ... #ColorFG#
X    =(#S#*5)R
Y    =r
W    =(#S#*(#SkinWidth#-90))

[ColorFGInput]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=255,255,255
Command1 =[!WriteKeyValue Variables "ColorFG" "$UserInput$" "#@#Variables.inc"][!Refresh *]
DefaultValue=#ColorFG#
SolidColor  =0,0,0
InputLimit  =11
X=[ColorFG:X]
Y=[ColorFG:Y]
W=[ColorFG:W]
H=[ColorFG:H]

[ColorBGSquare]
Meter =Shape
MeterStyle=Swatch
Shape =Rectangle 0,0,(#FontSZ#+2),(#FontSZ#+2) | Extend Mods | FillColor #ColorFG#
Shape2=Rectangle 1,1,(#FontSZ#+0),(#FontSZ#+0) | Extend Mods | FillColor #ColorBG#

[ColorBG]
Meter=String
MeterStyle    =OptionIT
Text =Background Color ... #ColorBG#
X    =(#S#*5)R
Y    =r
W    =(#S#*(#SkinWidth#-90))

[ColorBGInput]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=255,255,255
Command1 =[!WriteKeyValue Variables "ColorBG" "$UserInput$" "#@#Variables.inc"][!Refresh *]
DefaultValue=#ColorBG#
SolidColor  =0,0,0
InputLimit  =11
X=[ColorBG:X]
Y=[ColorBG:Y]
W=[ColorBG:W]
H=[ColorBG:H]

[ColorA1Square]
Meter=Shape
MeterStyle=Swatch
Shape=Rectangle 0,0,(#FontSZ#+2),(#FontSZ#+2) | Extend Mods | FillColor #ColorA1#

[ColorA1]
Meter=String
MeterStyle    =OptionIT
Text =Accent Color 1  ... #ColorA1#
X    =(#S#*5)R
Y    =r
W    =(#S#*(#SkinWidth#-90))

[ColorA1Input]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=255,255,255
Command1 =[!WriteKeyValue Variables "ColorA1" "$UserInput$" "#@#Variables.inc"][!Refresh *]
DefaultValue=#ColorA1#
SolidColor  =0,0,0
InputLimit  =11
X=[ColorA1:X]
Y=[ColorA1:Y]
W=[ColorA1:W]
H=[ColorA1:H]

[ColorA2Square]
Meter=Shape
MeterStyle=Swatch
Shape=Rectangle 0,0,(#FontSZ#+2),(#FontSZ#+2) | Extend Mods | FillColor #ColorA2#

[ColorA2]
Meter=String
MeterStyle    =OptionIT
Text =Accent Color 2 ... #ColorA2#
X    =(#S#*5)R
Y    =r
W    =(#S#*(#SkinWidth#-90))

[ColorA2Input]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=255,255,255
Command1 =[!WriteKeyValue Variables "ColorA2" "$UserInput$" "#@#Variables.inc"][!Refresh *]
DefaultValue=#ColorA2#
SolidColor  =0,0,0
InputLimit  =11
X=[ColorA2:X]
Y=[ColorA2:Y]
W=[ColorA2:W]
H=[ColorA2:H]

; ----------------------------------------- Background Modifiers

[Section3]
Meter=String
MeterStyle=Section
FontColor =#Accent3#
Text =< General Options >

[Scale]
Meter=String
MeterStyle    =OptionIT
Text =Scale ... #Scale#

[ScaleInput]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=255,255,255
Command1 =[!WriteKeyValue Variables "Scale" "$UserInput$" "#@#Variables.inc"][!Refresh *]
DefaultValue=#Scale#
SolidColor  =0,0,0
InputNumber =1
X=[Scale:X]
Y=[Scale:Y]
W=[Scale:W]
H=[Scale:H]

[Border]
Meter=String
MeterStyle=OptionYN
Text =Border ... #Border#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#Border#=1 ? 0:1)" "#@#Variables.inc"][!Refresh *]

[ShadowR]
Meter=String
MeterStyle    =OptionIT
Text =Shadow Radius ... #ShadowR#

[ShadowRInput]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=255,255,255
Command1 =[!WriteKeyValue Variables "ShadowR" "$UserInput$" "#@#Variables.inc"][!Refresh *]
DefaultValue=#ShadowR#
SolidColor  =0,0,0
InputNumber =1
X=[ShadowR:X]
Y=[ShadowR:Y]
W=[ShadowR:W]
H=[ShadowR:H]

[Alpha]
Meter=String
MeterStyle    =OptionIT
Text =Background Alpha ... #Alpha#

[AlphaInput]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=255,255,255
Command1 =[!WriteKeyValue Variables "Alpha" "(Clamp($UserInput$, 0, 255))" "#@#Variables.inc"][!Refresh *]
DefaultValue=#Alpha#
SolidColor  =0,0,0
InputNumber =1
InputLimit  =3
X=[Alpha:X]
Y=[Alpha:Y]
W=[Alpha:W]
H=[Alpha:H]

[Blur]
Meter=String
MeterStyle=OptionYN
Text =Blur ... #Blur#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#Blur#=1 ? 0:1)" "#@#Variables.inc"][!Refresh *]

[Font]
Meter=String
MeterStyle    =OptionIT
Text =Font ... #Font#

[FontInput]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=255,255,255
Command1 =[!WriteKeyValue Variables "Font" "$UserInput$" "#@#Variables.inc"][!Refresh *]
DefaultValue=#Font#
SolidColor  =0,0,0
X=[Font:X]
Y=[Font:Y]
W=[Font:W]
H=[Font:H]

[FontSZ]
Meter=String
MeterStyle    =OptionIT
Text =Font Size ... #FontSZ#

[FontSZInput]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=255,255,255
Command1 =[!WriteKeyValue Variables "FontSZ" "$UserInput$" "#@#Variables.inc"][!Refresh *]
DefaultValue=#FontSZ#
SolidColor  =0,0,0
InputNumber =1
InputLimit  =2
X=[FontSZ:X]
Y=[FontSZ:Y]
W=[FontSZ:W]
H=[FontSZ:H]

[AA]
Meter=String
MeterStyle=OptionYN
Text =Antialiasing ... #AA#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#AA#=1 ? 0:1)" "#@#Variables.inc"][!Refresh *]

; ----------------------------------------- Screenfetch

[Section4]
Meter=String
MeterStyle=Section
FontColor =#Accent1#
Text =< Screenfetch --- >

[24HR]
Meter=String
MeterStyle=OptionYN
Text =24 Hour Time ... #24HR#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#24HR#=1 ? 0:1)" "#@#Variables.inc"][!Refresh "#RootConfig#\Power"][!Refresh]

[AMPM]
Meter=String
MeterStyle=OptionYN
Text =AM/PM Indicator ... #AMPM#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#AMPM#=1 ? 0:1)" "#@#Variables.inc"][!Refresh "#RootConfig#\Power"][!Refresh]

[BG]
Meter=String
MeterStyle=OptionYN
Text =Sectioned Background ... #BG#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#BG#=1 ? 0:1)" "#@#Variables.inc"][!Refresh "#RootConfig#\Power"][!Refresh]

; ----------------------------------------- Media 

[Section5]
Meter=String
MeterStyle=Section
FontColor =#Accent2#
Text =< Media -------- >

[Align]
Meter=String
MeterStyle=OptionIT
Text =Alignment ... #Align#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "[AlignString]" "#@#Variables.inc"][!Refresh "#RootConfig#\Media"][!Refresh]

[AlignCalc]
Measure =String
String  =#Align#

IfMatch =Left
IfMatch2=Center
IfMatch3=Right
IfMatchAction =[!SetOption AlignString "String" "Center"]
IfMatchAction2=[!SetOption AlignString "String" "Right"]
IfMatchAction3=[!SetOption AlignString "String" "Left"]

[AlignString]
Measure=String
String =

[Album]
Meter=String
MeterStyle=OptionYN
Text =Album Text ... #Album#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#Album#=1 ? 0:1)" "#@#Variables.inc"][!Refresh "#RootConfig#\Media"][!Refresh]

[CoverP]
Meter=String
MeterStyle=OptionYN
Text =Cover Padding ... #CoverP#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#CoverP#=1 ? 0:1)" "#@#Variables.inc"][!Refresh "#RootConfig#\Media\Cover"][!Refresh]

[ProgType]
Meter=String
MeterStyle=OptionYN
Text =Progress Bar Type ... #ProgType#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#ProgType#=1 ? 0:1)" "#@#Variables.inc"][!Refresh "#RootConfig#\Media"][!Refresh]


[Vis]
Meter=String
MeterStyle=OptionYN
Text =Visualizer ... #Vis#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#Vis#=1 ? 0:1)" "#@#Variables.inc"][!Refresh "#RootConfig#\Media"][!Refresh]

[BarW]
Meter=String
MeterStyle    =OptionIT
Text =Visualizer Bar Width ... #BarW#

[BarWInput]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=255,255,255
Command1 =[!WriteKeyValue Variables "BarW" "$UserInput$" "#@#Variables.inc"][!Refresh "#RootConfig#\Media"][!Refresh]
DefaultValue=#BarW#
SolidColor  =0,0,0
InputNumber =1
InputLimit  =1
X=[BarW:X]
Y=[BarW:Y]
W=[BarW:W]
H=[BarW:H]

[Smooth]
Meter=String
MeterStyle=OptionYN
Text =Visualizer Smoothing ... #Smooth#

LeftMouseUpAction=[!WriteKeyValue Variables "#CurrentSection#" "(#Smooth#=1 ? 0:1)" "#@#Variables.inc"][!Refresh "#RootConfig#\Media"][!Refresh]

; ----------------------------------------- Scrolling

[Scroll]
Measure =Calc
Formula =0

[ScrollBorder]
Meter =Shape
Shape =Rectangle 0,0,#SkinWidth#,6     | Extend Mods | FillColor #ColorBG#,(#Alpha#=255 ? 255:0)
Shape2=Rectangle 4,4,(#SkinWidth#-8),2 | Extend Mods | FillColor #ColorA2#,(#Alpha#=255 ? (#Alpha#/4):0)

Shape3=Rectangle 0,(#SkinHeight#-6),#SkinWidth#,6     | Extend Mods | FillColor #ColorBG#,(#Alpha#=255 ? 255:0)
Shape4=Rectangle 4,(#SkinHeight#-6),(#SkinWidth#-8),2 | Extend Mods | FillColor #ColorA2#,(#Alpha#=255 ? (#Alpha#/4):0)
Mods  =Scale #S#,#S#,0,0 | StrokeWidth 0
Hidden=(#Border#=1 ? 0:1)
X     =(#S#*#ShadowR#)
Y     =(#S#*#ShadowR#)

[Drag]
Measure=Plugin
Plugin =Mouse
Group  =Progress
LeftMouseDragAction=[!SetOption Scroll "Formula" "Clamp((#S#*($MouseY$/((#SkinHeight#-100)/100))-(#ScrollH#/10)),0,100)"][!UpdateMeasure Scroll][!Update][!Redraw]
LeftMouseUpAction  =[!WriteKeyValue Scroll "Formula" "[Scroll]"][!CommandMeasure Drag "Stop"]
RelativeToSkin     =1
RequireDragging    =1
