[Rainmeter]
Update=1000
AccurateText=1

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc

; Change this to your desired color (Red, Green, Blue, Transparency 0-255)
Color=#ColorFG#
; Size of the box
BoxWidth=1920
BoxHeight=1080

[MeterBackground]
Meter=Shape
; Creates a rectangle
Shape=Rectangle 0,0,#BoxWidth#,#BoxHeight# | Fill Color #Color# | StrokeWidth 0
