[Rainmeter]
Update      =-1
AccurateText=1

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Players/#Plugin#.inc
SkinHeight=20
CurveRad  =2

; ----------------------------------------- Controls

[Next]
Meter =Shape
Shape =Path Tri1 | Scale #S#,#S#,0,0 | StrokeWidth 0 | FillColor #ColorB2#
Shape2=Path Tri2 | Scale #S#,#S#,0,0 | StrokeWidth 0 | FillColor #ColorB2#
Shape3=Rectangle 0,0,(#SkinWidth#/3),#SkinHeight# | Scale #S#,#S#,0,0 | StrokeWidth 0 | FillColor 0,0,0,1
Tri1  =0,#CurveRad# | LineTo 0,(#SkinHeight#-#CurveRad#) | CurveTo #CurveRad#,(#SkinHeight#-#CurveRad#),0,#SkinHeight# | LineTo 10,(#SkinHeight#+#CurveRad#/2)
Tri2  =0,0