[Rainmeter]
Update=1000
AccurateText=1
ContextTitle=Settings
ContextAction=[!ActivateConfig "#RootConfig#" "Settings.ini"][!Move (#CurrentConfigX#+(#S#*#SkinWidth#)+10) #CurrentConfigY# "#RootConfig#"]

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc
@Include4=#@#Players/#Plugin#.inc
SkinWidth =860
SkinHeight=545

; Change only this line to switch images
CurrentImage=KaguIro.jpg

[ImageMeter]
Meter=Image
ImageName=#@#Images\#CurrentImage#
DynamicVariables=1
PreserveAspectRatio=2
W=840
H=525
X=10
Y=10