[Rainmeter]
Update        =150
AccurateText  =1
ContextTitle  =Settings
ContextAction =[!ActivateConfig "#RootConfig#" "Settings.ini"][!Move (#CurrentConfigX#+(#S#*#SkinWidth#)+10) #CurrentConfigY# "#RootConfig#"]
ContextTitle2 =App Settings
ContextAction2=["#@#AppVars.inc"]

OnRefreshAction=[!HideMeterGroup 2][!Redraw]

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc
@Include4=#@#AppVars.inc
SkinWidth =300
SkinHeight=60

; ----------------------------------------- Loop

[Loop]
Measure   =Loop
StartValue=0
EndValue  =1
LoopCount =1

IfCondition =(Loop=1)
IfTrueAction=[!SetOptionGroup Apps "InlineSetting3" "Color|#ColorFG#"][!SetOptionGroup Apps "SolidColor" "#ColorFG#,40"][!UpdateMeterGroup Apps][!Redraw]

; ----------------------------------------- Apps

[App1]
Meter     =String
MeterStyle=App
Text      =#AppName1#
X         =(#S#*(#SkinWidth#/6-(#SkinWidth#/20))+#ShadowR#)
Y         =(#S#*(#SkinHeight#/2)+#ShadowR#)
LeftMouseUpAction=[!CommandMeasure Loop "Reset"][#AppPath1#]

[App2]
Meter     =String
MeterStyle=App
Text      =#AppName2#
LeftMouseUpAction=[!CommandMeasure Loop "Reset"][#AppPath2#]

[App3]
Meter     =String
MeterStyle=App
Text      =#AppName3#
LeftMouseUpAction=[!CommandMeasure Loop "Reset"][#AppPath3#]

[App4]
Meter     =String
MeterStyle=App
Text      =#AppName4#
LeftMouseUpAction=[!CommandMeasure Loop "Reset"][#AppPath4#]

[NextPage]
Meter     =String
MeterStyle=App
Text      =[\xEA07]
InlineSetting    =Face |Siji
InlineSetting2   =Size |(#S#*9)
LeftMouseUpAction=[!ShowMeterGroup 2][!HideMeterGroup 1][!UpdateMeterGroup Apps][!Redraw]

[PrevPage]
Meter     =String
Group     =Apps | 2
MeterStyle=App
Text      =[\xEA08]
X         =(#S#*(#SkinWidth#/6-(#SkinWidth#/20))+#ShadowR#)
Y         =(#S#*(#SkinHeight#/2)+#ShadowR#)
InlineSetting    =Face|Siji
InlineSetting2   =Size|(#S#*9)
LeftMouseUpAction=[!HideMeterGroup 2][!ShowMeterGroup 1][!UpdateMeterGroup Apps][!Redraw]

[App5]
Meter     =String
Group     =Apps | 2
MeterStyle=App
Text      =#AppName5#
LeftMouseUpAction=[!CommandMeasure Loop "Reset"][#AppPath5#]

[App6]
Meter     =String
Group     =Apps | 2
MeterStyle=App
Text      =#AppName6#
LeftMouseUpAction=[!CommandMeasure Loop "Reset"][#AppPath6#]

[App7]
Meter     =String
Group     =Apps | 2
MeterStyle=App
Text      =#AppName7#
LeftMouseUpAction=[!CommandMeasure Loop "Reset"][#AppPath7#]

[App8]
Meter     =String
Group     =Apps | 2
MeterStyle=App
Text      =#AppName8#
LeftMouseUpAction=[!CommandMeasure Loop "Reset"][#AppPath8#]