[Rainmeter]
Update        =-1
AccurateText  =1
ContextTitle  =Settings
ContextAction =[!ActivateConfig "#RootConfig#" "Settings.ini"][!Move (#CurrentConfigX#+(#S#*#SkinWidth#)+10) #CurrentConfigY# "#RootConfig#"]
ContextTitle2 =Toggle Raw Text
ContextAction2=[!WriteKeyValue Variables "RawString" "[RawCalc]"][!Refresh]

; ----------------------------------------- Inclusions

[Variables]
@Include1=#@#Variables.inc
@Include2=#@#Styles.inc
@Include3=#@#Modules/Background.inc
SkinWidth =300
SkinHeight=120
LineBreak =##
StrikeThru=~~
Underline =__
Bolded    =\*\*

RawString =0
RawText   =__Notes:__## - Wish me a happy birthday #### - Release Skin#### - ~~Add more settings~~

; ----------------------------------------- Text Display

[Text]
Meter     =String
MeterStyle=Text

[TextInput]
Measure  =Plugin
Plugin   =InputText
FontFace =#Font#
FontSize =(#S#*#FontSZ#)
FontColor=#ColorFG#
Command1 =[!WriteKeyValue Variables "RawText" "$UserInput$"][!Refresh]
DefaultValue=#RawText#
SolidColor  =#ColorBG#
X=[Text:X]
Y=[Text:Y]
W=[Text:W]
H=[Text:H]

; ----------------------------------------- Text Strings

[TextString1]
Measure=String
String =#RawText#

[TextString0]
Measure   =String
String    =#RawText#
Substitute="#LineBreak#":"#CRLF#"

; ----------------------------------------- Raw Text

[RawCalc]
Measure=Calc
Formula=(#RawString#=1 ? 0:1)

IfCondition  =(#RawString#=1)
IfTrueAction =[!SetOption Text "InlineSetting6" "None"][!SetOption Text "InlineSetting7" "None"][!SetOption Text "InlineSetting8" "None"]
