[Variables]

AppName1=Youtube
AppPath1=Chrome.exe --app=https://www.youtube.com/feed/subscriptions

AppName2=Devart
AppPath2=https://eldog-02.deviantart.com/

AppName3=/r/RM
AppPath3=https://www.reddit.com/r/Rainmeter

AppName4=/r/ADT
AppPath4=https://www.reddit.com/r/AndroidThemes

AppName5=RM
AppPath5=!Manage

AppName6=Log
AppPath6=!About

AppName7=Refresh#CRLF#All
AppPath7=!RefreshApp

AppName8=Windows#CRLF#Tweaks
AppPath8="D:\WindowsTweaks"