[Variables]

; ----------------------------------------- Media Player

Plugin=Web
; NowPlaying - Spotify - Web - GPMDP

Player=Web
; AIMP - iTunes - Spotify - Winamp - WMP - CAD (Foobar & Musicbee)
; Only applicable if using the NowPlaying / Spotify plugins

; ----------------------------------------- General

ColorFG=94,92,87
ColorBG=195,175,61
ColorA1=211,206,140
ColorA2=94,92,87
; Foreground/Background/Accent Colors

Border =1
ShadowR=0
Alpha  =255
Blur   =0
; Background Modifiers

Scale  =1

Font   =Scientifica
FontSZ =9
; Font/Font Size

AA     =0
; Font Antialiasing

; ----------------------------------------- Screenfetch

24Hr=1
AMPM=0

BG  =1

; ----------------------------------------- Media

Align =Left
; Left - Center - Right

Album =0
; Displays the current album

Vis   =1

BarW  =1
; Width of visualizer's bars
Smooth=0
; Smooths the visualizer's movements

CoverP=0
; Pads the cover if border is enabled

ProgType=1

; ----------------------------------------- Misc.

S=#Scale#
